"""google sign-in

Revision ID: 05d443f38520
Revises: 1f7ce534546c
Create Date: 2026-10-09 09:04:07.412387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d443f38520'
down_revision = '1f7ce534546c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_client_id', sa.String(length=255), nullable=True),
    sa.Column('google_client_secret', sa.Text(), nullable=True),
    sa.Column('allowed_domains', sa.String(length=500), nullable=True),
    sa.Column('shared_password_disabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    op.drop_table('signin_settings')
    # ### end Alembic commands ###
