"""automation rules

Adds the rule engine's tables and converts every legacy ticket automation
(ticket category → device action) into an equivalent rule, so nothing a
district already set up stops working. The legacy ticket_automation table
is left in place, unused, so rolling back to the previous image still works.

Revision ID: 0617146b9543
Revises: 4a5368f32367
Create Date: 2026-10-08 09:47:15.525298

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0617146b9543'
down_revision = '4a5368f32367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('match', sa.String(length=3), server_default='all', nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('template_key', sa.String(length=60), nullable=True),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rule_trigger'), ['trigger'], unique=False)

    op.create_table('automation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('subject_label', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'dedupe_key', name='uq_automation_run_dedupe')
    )
    with op.batch_alter_table('automation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_run_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('pending_device_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('params', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_pending_device_action_rule_id', 'automation_rule', ['rule_id'], ['id'])

    # ### end Alembic commands ###
    _convert_ticket_automations()


LEGACY_LABELS = {'profile_clear': 'clear the Chromebook\'s profiles', 'disable_google': 'disable it in Google',
                 'send_to_repair': 'send it to repair', 'move_device': 'move it to an org unit'}


def _convert_ticket_automations():
    conn = op.get_bind()
    legacy = sa.table('ticket_automation', sa.column('id'), sa.column('ticket_category_id'), sa.column('action_type'),
                      sa.column('require_confirmation'), sa.column('is_active'), sa.column('repair_category_id'),
                      sa.column('target_org_unit_path'))
    category = sa.table('ticket_category', sa.column('id'), sa.column('name'))
    rows = conn.execute(
        sa.select(legacy.c.ticket_category_id, legacy.c.action_type, legacy.c.require_confirmation,
                  legacy.c.is_active, legacy.c.repair_category_id, legacy.c.target_org_unit_path, category.c.name)
        .select_from(legacy.outerjoin(category, legacy.c.ticket_category_id == category.c.id))
        .order_by(legacy.c.id)
    ).fetchall()
    if not rows:
        return
    rule = sa.table('automation_rule', sa.column('name', sa.String), sa.column('description', sa.Text),
                    sa.column('trigger', sa.String), sa.column('match', sa.String), sa.column('conditions', sa.JSON),
                    sa.column('actions', sa.JSON), sa.column('enabled', sa.Boolean), sa.column('run_count', sa.Integer),
                    sa.column('created_by', sa.String), sa.column('created_at', sa.DateTime),
                    sa.column('updated_at', sa.DateTime))
    now = datetime.utcnow()
    new_rules = []
    for cat_id, action_type, confirm, active, repair_cat, org_unit, cat_name in rows:
        params = {'confirm': bool(confirm)}
        if action_type == 'send_to_repair':
            params['repair_category'] = str(repair_cat) if repair_cat else ''
        if action_type == 'move_device':
            params['org_unit'] = org_unit or ''
        # Every row gets the same keys: bulk_insert compiles one statement from the first row.
        new_rules.append(dict(
            name=f'{cat_name or "Category " + str(cat_id)} tickets: {LEGACY_LABELS.get(action_type, action_type)}'[:160],
            description='Converted from the old ticket automation for this category.',
            trigger='ticket.created', match='all',
            conditions=[{'field': 'ticket.category', 'op': 'eq', 'value': str(cat_id)},
                        {'field': 'ticket.has_device', 'op': 'true', 'value': None}],
            actions=[{'type': action_type, 'params': params}],
            enabled=bool(active), run_count=0, created_by='Upgrade', created_at=now, updated_at=now,
        ))
    op.bulk_insert(rule, new_rules)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_device_action', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pending_device_action_rule_id', type_='foreignkey')
        batch_op.drop_column('params')
        batch_op.drop_column('rule_id')

    with op.batch_alter_table('automation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_run_rule_id'))
        batch_op.drop_index(batch_op.f('ix_automation_run_created_at'))

    op.drop_table('automation_run')
    with op.batch_alter_table('automation_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rule_trigger'))

    op.drop_table('automation_rule')
    # ### end Alembic commands ###
