"""directory connection settings

Revision ID: 0728a61e1835
Revises: 0d7873d7aba6
Create Date: 2026-10-08 14:32:39.622349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0728a61e1835'
down_revision = '0d7873d7aba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servers', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('base_dn', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bind_user', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bind_password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ca_pem', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_settings', schema=None) as batch_op:
        batch_op.drop_column('ca_pem')
        batch_op.drop_column('bind_password')
        batch_op.drop_column('bind_user')
        batch_op.drop_column('base_dn')
        batch_op.drop_column('servers')

    # ### end Alembic commands ###
