"""add branding_settings and site logo

Revision ID: 07c71bcf7352
Revises: 7ae4b44e9384
Create Date: 2026-08-11 14:44:46.900068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c71bcf7352'
down_revision = '7ae4b44e9384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=120), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('primary_color_raw', sa.String(length=7), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_dim_color', sa.String(length=7), nullable=True),
    sa.Column('accent_text_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_text_color', sa.String(length=7), nullable=True),
    sa.Column('tertiary_color', sa.String(length=7), nullable=True),
    sa.Column('tertiary_text_color', sa.String(length=7), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')

    op.drop_table('branding_settings')
    # ### end Alembic commands ###
