"""directory settings

Revision ID: 0d7873d7aba6
Revises: 0617146b9543
Create Date: 2026-10-08 13:31:54.602077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7873d7aba6'
down_revision = '0617146b9543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('user_containers', sa.JSON(), nullable=True),
    sa.Column('computer_containers', sa.JSON(), nullable=True),
    sa.Column('trusted_certs', sa.JSON(), nullable=True),
    sa.Column('tree', sa.JSON(), nullable=True),
    sa.Column('tree_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_summary', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directory_settings')
    # ### end Alembic commands ###
