"""warranty settings

Revision ID: 1f7ce534546c
Revises: 86776d592215
Create Date: 2026-10-09 09:00:47.016725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7ce534546c'
down_revision = '86776d592215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warranty_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dell_client_id', sa.String(length=255), nullable=True),
    sa.Column('dell_client_secret', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_summary', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty_settings')
    # ### end Alembic commands ###
