"""add asset number range default flag

Revision ID: 242b96dbf779
Revises: 6095b1c38ffb
Create Date: 2026-08-20 09:51:20.585394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242b96dbf779'
down_revision = '6095b1c38ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here (not just the model's Python-side
    # default=False) — without it, adding a NOT NULL column to a table that
    # already has rows (any range reserved before this migration) fails with
    # "column contains null values".
    with op.batch_alter_table('asset_number_range', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_number_range', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
