"""add google org unit cache on person

Revision ID: 2b87ceab63de
Revises: f99f57a442f8
Create Date: 2026-08-27 11:28:08.959255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b87ceab63de'
down_revision = 'f99f57a442f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_org_unit', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_last_sync_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('google_last_sync_at')
        batch_op.drop_column('google_org_unit')

    # ### end Alembic commands ###
