"""add ticket_charge line items, drop single ticket fee columns

Revision ID: 38d790d0305a
Revises: ffa09543e108
Create Date: 2026-08-20 12:53:26.364609

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d790d0305a'
down_revision = 'ffa09543e108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_charge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_charge_ticket_id'), ['ticket_id'], unique=False)

    # --- data migration: fold each ticket's single fee_amount into one
    # TicketCharge row before the old columns are dropped, so existing
    # billing history survives the switch to itemized charges ---
    ticket = sa.table('ticket',
        sa.column('id', sa.Integer),
        sa.column('category_id', sa.Integer),
        sa.column('fee_charged', sa.Boolean),
        sa.column('fee_amount', sa.Numeric(8, 2)),
        sa.column('paid_at', sa.DateTime),
    )
    ticket_category = sa.table('ticket_category',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
    )
    ticket_charge = sa.table('ticket_charge',
        sa.column('ticket_id', sa.Integer),
        sa.column('description', sa.Text),
        sa.column('amount', sa.Numeric(8, 2)),
        sa.column('paid_at', sa.DateTime),
        sa.column('created_at', sa.DateTime),
    )
    conn = op.get_bind()
    now = datetime.utcnow()
    rows = conn.execute(
        sa.select(ticket.c.id, ticket.c.fee_amount, ticket.c.paid_at, ticket_category.c.name)
        .select_from(ticket.outerjoin(ticket_category, ticket_category.c.id == ticket.c.category_id))
        .where(ticket.c.fee_charged.is_(True))
    ).fetchall()
    for row in rows:
        conn.execute(ticket_charge.insert().values(
            ticket_id=row.id, description=row.name or 'Ticket fee',
            amount=row.fee_amount or 0, paid_at=row.paid_at, created_at=now,
        ))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('fee_charged')
        batch_op.drop_column('fee_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_amount', sa.NUMERIC(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fee_charged', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('paid_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('ticket_charge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_charge_ticket_id'))

    op.drop_table('ticket_charge')
    # ### end Alembic commands ###
