"""person identities and device records

Revision ID: 4a5368f32367
Revises: a324cf393d24
Create Date: 2026-10-08 09:21:04.848349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5368f32367'
down_revision = 'a324cf393d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('join_type', sa.String(length=20), nullable=True),
    sa.Column('os_name', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=120), nullable=True),
    sa.Column('directory_path', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registry_id'], ['asset_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_key', name='uq_device_record_source_key')
    )
    with op.batch_alter_table('device_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_record_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_record_registry_id'), ['registry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_record_serial_number'), ['serial_number'], unique=False)

    op.create_table('person_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('directory_path', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('suggested_person_id', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['suggested_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_key', name='uq_person_identity_source_key')
    )
    with op.batch_alter_table('person_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_identity_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_identity_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###
    _backfill_identities()


def _backfill_identities():
    """Seed accounts from data that already exists, done in Python so it
    reads JSON the same way on SQLite and Postgres:
    - a profile merged into another (custom_fields.merged_into) becomes an
      'alias' email on the surviving profile;
    - a person the Google people sync has matched (google_last_sync_at set)
      gets a 'google' account keyed by email (the sync re-keys nothing; it
      matches this row by email on its next run)."""
    import json
    from datetime import datetime
    conn = op.get_bind()
    people = conn.execute(sa.text(
        'SELECT id, email, custom_fields, google_org_unit, google_last_sync_at FROM person')).fetchall()
    ids = {row[0] for row in people}
    now = datetime.utcnow()
    rows, seen = [], set()
    for pid, email, custom, org_unit, synced_at in people:
        email = (email or '').strip().lower()
        if not email:
            continue
        if isinstance(synced_at, str):  # SQLite returns timestamps as text
            try:
                synced_at = datetime.fromisoformat(synced_at)
            except ValueError:
                synced_at = None
        if isinstance(custom, str):
            try:
                custom = json.loads(custom)
            except ValueError:
                custom = None
        target = (custom or {}).get('merged_into')
        if target in ids and ('alias', email) not in seen:
            # every row carries every column — bulk_insert rejects mixed key sets
            rows.append(dict(person_id=target, source='alias', external_key=email, email=email,
                             directory_path=None, last_synced_at=None, created_at=now))
            seen.add(('alias', email))
        elif synced_at and ('google', email) not in seen:
            rows.append(dict(person_id=pid, source='google', external_key=email, email=email,
                             directory_path=org_unit, last_synced_at=synced_at, created_at=now))
            seen.add(('google', email))
    if rows:
        table = sa.table('person_identity', sa.column('person_id', sa.Integer), sa.column('source', sa.String),
                         sa.column('external_key', sa.String), sa.column('email', sa.String),
                         sa.column('directory_path', sa.String), sa.column('last_synced_at', sa.DateTime),
                         sa.column('created_at', sa.DateTime))
        op.bulk_insert(table, rows)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_identity_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_identity_email'))

    op.drop_table('person_identity')
    with op.batch_alter_table('device_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_record_serial_number'))
        batch_op.drop_index(batch_op.f('ix_device_record_registry_id'))
        batch_op.drop_index(batch_op.f('ix_device_record_hostname'))

    op.drop_table('device_record')
    # ### end Alembic commands ###
