"""add ticket automation and pending device action tables

Revision ID: 5fd2571d910e
Revises: 5c018e6e9858
Create Date: 2026-09-16 10:41:16.577951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd2571d910e'
down_revision = '5c018e6e9858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_automation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_category_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('require_confirmation', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_category_id'], ['ticket_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_category_id')
    )
    op.create_table('pending_device_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_label', sa.String(length=160), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_device_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_device_action_asset_tag'), ['asset_tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_device_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_device_action_asset_tag'))

    op.drop_table('pending_device_action')
    op.drop_table('ticket_automation')
    # ### end Alembic commands ###
