"""add branding logo_background

Revision ID: 6095b1c38ffb
Revises: e6d53dbc7f64
Create Date: 2026-08-19 15:38:30.642875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6095b1c38ffb'
down_revision = 'e6d53dbc7f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_background', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.drop_column('logo_background')

    # ### end Alembic commands ###
