"""add sync schedule for automatic google syncs

Revision ID: 610fb8a73888
Revises: 809491a414e2
Create Date: 2026-09-08 10:39:16.383487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610fb8a73888'
down_revision = '809491a414e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_summary', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_schedule')
    # ### end Alembic commands ###
