"""add insurance_opted_in and acknowledged_by columns

Revision ID: 7ae4b44e9384
Revises: ff757c46630a
Create Date: 2026-08-05 10:49:47.896545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae4b44e9384'
down_revision = 'ff757c46630a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged_by', sa.String(length=160), nullable=True))

    with op.batch_alter_table('loaner_checkout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged_by', sa.String(length=160), nullable=True))

    # server_default is required here (not just the model's Python-side
    # default=False) — without it, adding a NOT NULL column to a table that
    # already has rows (every existing Person on staging/production) fails
    # with "column contains null values". Postgres 11+ applies a constant
    # default like this as a fast metadata-only change, not a full table rewrite.
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_opted_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('insurance_opted_in')

    with op.batch_alter_table('loaner_checkout', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_by')

    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_by')

    # ### end Alembic commands ###
