"""add loaner label for physical tracking / dymo labels

Revision ID: 809491a414e2
Revises: 2b87ceab63de
Create Date: 2026-09-08 09:54:50.656404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809491a414e2'
down_revision = '2b87ceab63de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loaner_label', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_column('loaner_label')

    # ### end Alembic commands ###
