"""google sign-in history and mismatch reviews

Revision ID: 845a53a596b7
Revises: e58eeff10b3e
Create Date: 2026-10-07 09:49:05.617043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845a53a596b7'
down_revision = 'e58eeff10b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signin_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('signin_email', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.String(length=160), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag', 'signin_email', name='uq_signin_review_asset_email')
    )
    with op.batch_alter_table('signin_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signin_review_asset_tag'), ['asset_tag'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_recent_users', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('google_last_activity', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('google_last_activity')
        batch_op.drop_column('google_recent_users')

    with op.batch_alter_table('signin_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signin_review_asset_tag'))

    op.drop_table('signin_review')
    # ### end Alembic commands ###
