"""parts inventory

Revision ID: 86776d592215
Revises: 0728a61e1835
Create Date: 2026-10-09 08:52:24.685342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86776d592215'
down_revision = '0728a61e1835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('fits_models', sa.JSON(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('vendor', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repair.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_movement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_movement_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_movement_repair_id'), ['repair_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_movement_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_movement_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_part_movement_repair_id'))
        batch_op.drop_index(batch_op.f('ix_part_movement_part_id'))
        batch_op.drop_index(batch_op.f('ix_part_movement_created_at'))

    op.drop_table('part_movement')
    op.drop_table('part')
    # ### end Alembic commands ###
