"""add google org units and mapping scope

Revision ID: 8cf0a18e6fe9
Revises: 9da48fb20237
Create Date: 2026-08-26 13:49:27.746008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf0a18e6fe9'
down_revision = '9da48fb20237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_org_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_unit_path', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_unit_path')
    )
    with op.batch_alter_table('google_field_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_unit_scope', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_field_mapping', schema=None) as batch_op:
        batch_op.drop_column('org_unit_scope')

    op.drop_table('google_org_unit')
    # ### end Alembic commands ###
