"""add loaner org unit push and grad year org unit mapping

Revision ID: 97cc81ae46aa
Revises: 0490dcc7d6a2
Create Date: 2026-08-27 10:48:24.491275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cc81ae46aa'
down_revision = '0490dcc7d6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grad_year_ou_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grad_year', sa.Integer(), nullable=False),
    sa.Column('org_unit_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grad_year')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loaner_org_unit_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('loaner_org_unit_path')

    op.drop_table('grad_year_ou_mapping')
    # ### end Alembic commands ###
