"""add custom fields and google field mapping

Revision ID: 9da48fb20237
Revises: 17cf2258465e
Create Date: 2026-08-26 12:00:49.223653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da48fb20237'
down_revision = '17cf2258465e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'field_key', name='uq_custom_field_entity_key')
    )
    op.create_table('google_field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('google_field', sa.String(length=120), nullable=False),
    sa.Column('target_field', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    op.drop_table('google_field_mapping')
    op.drop_table('custom_field')
    # ### end Alembic commands ###
