"""add kace field mapping table

Revision ID: a0e4e4acc67e
Revises: 610fb8a73888
Create Date: 2026-09-08 12:21:02.639140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e4e4acc67e'
down_revision = '610fb8a73888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kace_field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kace_field', sa.String(length=80), nullable=False),
    sa.Column('target_field', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kace_field_mapping')
    # ### end Alembic commands ###
