"""add category default price and ticket billing fields

Revision ID: a7a3160d0abc
Revises: cfc1968eb68e
Create Date: 2026-08-19 12:47:20.426122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a3160d0abc'
down_revision = 'cfc1968eb68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required on fee_charged (not just the model's
    # Python-side default=False) — without it, adding a NOT NULL column to a
    # table that may already have rows (staging/any local testing) fails with
    # "column contains null values".
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_charged', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ticket_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_category', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('fee_amount')
        batch_op.drop_column('fee_charged')

    # ### end Alembic commands ###
