"""help desk email, teams, canned replies, portals

Revision ID: b29ba2c34e9b
Revises: 05d443f38520
Create Date: 2026-10-09 09:59:57.142443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29ba2c34e9b'
down_revision = '05d443f38520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('portal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_secret_key', sa.Text(), nullable=True),
    sa.Column('payment_note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_user', sa.String(length=255), nullable=True),
    sa.Column('imap_password', sa.Text(), nullable=True),
    sa.Column('graph_tenant', sa.String(length=255), nullable=True),
    sa.Column('graph_client_id', sa.String(length=255), nullable=True),
    sa.Column('graph_client_secret', sa.Text(), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_summary', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['default_category_id'], ['ticket_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('canned_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_ref')
    )
    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_payment_incident_id'), ['incident_id'], unique=False)

    op.create_table('inbound_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('inbound_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_email_received_at'), ['received_at'], unique=False)

    op.create_table('ticket_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_key', sa.String(length=80), nullable=False),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('typing', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'actor_key', name='uq_ticket_presence_actor')
    )
    with op.batch_alter_table('ticket_presence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_presence_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_aue_date', sa.Date(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ticket_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('fk_ticket_team_id', 'team', ['team_id'], ['id'])

    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_requester', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')

    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.drop_column('from_requester')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_team_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ticket_team_id'))
        batch_op.drop_column('team_id')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('google_aue_date')

    with op.batch_alter_table('ticket_presence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_presence_ticket_id'))

    op.drop_table('ticket_presence')
    with op.batch_alter_table('inbound_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_email_received_at'))

    op.drop_table('inbound_email')
    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_payment_incident_id'))

    op.drop_table('fee_payment')
    op.drop_table('team_member')
    op.drop_table('canned_reply')
    op.drop_table('team')
    op.drop_table('mailbox_settings')
    op.drop_table('portal_settings')
    op.drop_table('portal_login')
    # ### end Alembic commands ###
