"""add user default landing page and default site

Revision ID: c3d6229be54a
Revises: c348ff4c2f39
Create Date: 2026-09-25 15:13:08.563059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d6229be54a'
down_revision = 'c348ff4c2f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_landing', sa.String(length=20), nullable=False, server_default='dashboard'))
        batch_op.add_column(sa.Column('default_site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_default_site_id', 'site', ['default_site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_default_site_id', type_='foreignkey')
        batch_op.drop_column('default_site_id')
        batch_op.drop_column('default_landing')

    # ### end Alembic commands ###
