"""add tickets, device model catalog, reserved asset ranges

Revision ID: cfc1968eb68e
Revises: 07c71bcf7352
Create Date: 2026-08-19 11:54:33.171650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc1968eb68e'
down_revision = '07c71bcf7352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_number_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('range_start', sa.Integer(), nullable=False),
    sa.Column('range_end', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('device_type', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'model_name', name='uq_device_model_make_model')
    )
    op.create_table('ticket_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag', sa.String(length=120), nullable=True),
    sa.Column('requester_person_id', sa.Integer(), nullable=True),
    sa.Column('requester_name', sa.String(length=160), nullable=True),
    sa.Column('requester_email', sa.String(length=160), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_category.id'], ),
    sa.ForeignKeyConstraint(['requester_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_asset_tag'), ['asset_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status'), ['status'], unique=False)

    op.create_table('ticket_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_label', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comment_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_model_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_asset_registry_device_model_id'), ['device_model_id'], unique=False)
        batch_op.create_foreign_key('fk_asset_registry_device_model_id', 'device_model', ['device_model_id'], ['id'])

    # server_default is required here (not just the model's Python-side
    # default=False) — without it, adding a NOT NULL column to a table that
    # already has rows (every existing User on staging/production) fails
    # with "column contains null values".
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_tickets', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_tickets')

    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_registry_device_model_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_asset_registry_device_model_id'))
        batch_op.drop_column('device_model_id')

    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comment_ticket_id'))

    op.drop_table('ticket_comment')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_site_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_created_at'))
        batch_op.drop_index(batch_op.f('ix_ticket_asset_tag'))

    op.drop_table('ticket')
    op.drop_table('ticket_category')
    op.drop_table('device_model')
    op.drop_table('asset_number_range')
    # ### end Alembic commands ###
