"""add favicon and customizable email templates

Revision ID: dd4a0ccdafab
Revises: bda56382de3d
Create Date: 2026-08-25 08:38:19.764562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4a0ccdafab'
down_revision = 'bda56382de3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loaner_overdue_subject', sa.String(length=200), nullable=True),
    sa.Column('loaner_overdue_body', sa.Text(), nullable=True),
    sa.Column('loaner_upcoming_subject', sa.String(length=200), nullable=True),
    sa.Column('loaner_upcoming_body', sa.Text(), nullable=True),
    sa.Column('loaner_nodate_subject', sa.String(length=200), nullable=True),
    sa.Column('loaner_nodate_body', sa.Text(), nullable=True),
    sa.Column('assignment_overdue_subject', sa.String(length=200), nullable=True),
    sa.Column('assignment_overdue_body', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.drop_column('favicon_filename')

    op.drop_table('email_settings')
    # ### end Alembic commands ###
