"""attachments, guardian contact, ticket and damage-notice emails

Revision ID: e58eeff10b3e
Revises: c3d6229be54a
Create Date: 2026-10-07 09:08:22.999253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58eeff10b3e'
down_revision = 'c3d6229be54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_owner', ['owner_type', 'owner_id'], unique=False)

    with op.batch_alter_table('email_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_received_subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ticket_received_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_reply_subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ticket_reply_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_resolved_subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ticket_resolved_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('damage_notice_subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('damage_notice_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_notifications_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_notified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('guardian_email', sa.String(length=160), nullable=True))

    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailed_to_requester', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.drop_column('emailed_to_requester')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('guardian_email')
        batch_op.drop_column('guardian_name')

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('guardian_notified_at')

    with op.batch_alter_table('email_settings', schema=None) as batch_op:
        batch_op.drop_column('ticket_notifications_enabled')
        batch_op.drop_column('damage_notice_body')
        batch_op.drop_column('damage_notice_subject')
        batch_op.drop_column('ticket_resolved_body')
        batch_op.drop_column('ticket_resolved_subject')
        batch_op.drop_column('ticket_reply_body')
        batch_op.drop_column('ticket_reply_subject')
        batch_op.drop_column('ticket_received_body')
        batch_op.drop_column('ticket_received_subject')

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index('ix_attachment_owner')

    op.drop_table('attachment')
    # ### end Alembic commands ###
