"""remove grad year ou push (devices-only push), add quick add support

Revision ID: f99f57a442f8
Revises: 97cc81ae46aa
Create Date: 2026-08-27 11:21:09.324172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99f57a442f8'
down_revision = '97cc81ae46aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grad_year_ou_mapping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grad_year_ou_mapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grad_year', sa.INTEGER(), nullable=False),
    sa.Column('org_unit_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grad_year')
    )
    # ### end Alembic commands ###
