"""baseline: full schema through the feature batch (purchase/warranty, repairs, fees, activity log, google loaner autodisable)

Revision ID: ff757c46630a
Revises: 
Create Date: 2026-08-04 13:30:49.839559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff757c46630a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_scan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_scan_asset_tag'), ['asset_tag'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('scanned_value', sa.String(length=120), nullable=True),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('person_name', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_asset_tag'), ['asset_tag'], unique=False)

    op.create_table('repair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=True),
    sa.Column('ticket_number', sa.String(length=80), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('person_name_snapshot', sa.String(length=160), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('expected_return_at', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_asset_tag'), ['asset_tag'], unique=False)

    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('google_loaner_autodisable_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('can_people', sa.Boolean(), nullable=False),
    sa.Column('can_devices', sa.Boolean(), nullable=False),
    sa.Column('can_devices_manage', sa.Boolean(), nullable=False),
    sa.Column('can_loaners', sa.Boolean(), nullable=False),
    sa.Column('can_loaner_checkinout', sa.Boolean(), nullable=False),
    sa.Column('can_checkinout', sa.Boolean(), nullable=False),
    sa.Column('can_repairs', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('asset_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=40), nullable=False),
    sa.Column('is_loaner', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_registry_asset_tag'), ['asset_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_registry_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_registry_is_loaner'), ['is_loaner'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_registry_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_registry_site_id'), ['site_id'], unique=False)

    op.create_table('kiosk_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_device_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_device_token'), ['token'], unique=True)

    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('grad_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_grad_year'), ['grad_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_site_id'), ['site_id'], unique=False)

    op.create_table('user_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_id', name='uq_user_site')
    )
    with op.batch_alter_table('user_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_site_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_site_user_id'), ['user_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('google_model', sa.String(length=120), nullable=True),
    sa.Column('google_org_unit', sa.String(length=255), nullable=True),
    sa.Column('google_recent_user', sa.String(length=255), nullable=True),
    sa.Column('google_last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('google_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_tag'), ['asset_tag'], unique=True)

    op.create_table('assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=160), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('condition_out', sa.String(length=255), nullable=True),
    sa.Column('condition_in', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_history_asset_tag'), ['asset_tag'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fee_charged', sa.Boolean(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_asset_tag'), ['asset_tag'], unique=False)

    op.create_table('loaner_checkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=160), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('condition_notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loaner_checkout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loaner_checkout_asset_tag'), ['asset_tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loaner_checkout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loaner_checkout_asset_tag'))

    op.drop_table('loaner_checkout')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_asset_tag'))

    op.drop_table('incident')
    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_history_asset_tag'))

    op.drop_table('assignment_history')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_asset_tag'))

    op.drop_table('asset')
    with op.batch_alter_table('user_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_site_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_site_site_id'))

    op.drop_table('user_site')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_site_id'))
        batch_op.drop_index(batch_op.f('ix_person_site'))
        batch_op.drop_index(batch_op.f('ix_person_is_active'))
        batch_op.drop_index(batch_op.f('ix_person_grad_year'))
        batch_op.drop_index(batch_op.f('ix_person_external_id'))
        batch_op.drop_index(batch_op.f('ix_person_email'))

    op.drop_table('person')
    with op.batch_alter_table('kiosk_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_device_token'))
        batch_op.drop_index(batch_op.f('ix_kiosk_device_site_id'))

    op.drop_table('kiosk_device')
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_registry_site_id'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_serial_number'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_is_loaner'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_device_type'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_asset_tag'))

    op.drop_table('asset_registry')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_site_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action'))

    op.drop_table('activity_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_name'))

    op.drop_table('site')
    with op.batch_alter_table('repair', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_asset_tag'))

    op.drop_table('repair')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_asset_tag'))

    op.drop_table('event')
    with op.batch_alter_table('audit_scan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_scan_asset_tag'))

    op.drop_table('audit_scan')
    # ### end Alembic commands ###
