"""add activity log ticket_id

Revision ID: ffa09543e108
Revises: 242b96dbf779
Create Date: 2026-08-20 10:51:19.627893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa09543e108'
down_revision = '242b96dbf779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_log_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_foreign_key('fk_activity_log_ticket_id', 'ticket', ['ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_log_ticket_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_log_ticket_id'))
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###
